---
- hosts: debian:&nexus
  tasks:
  - get_url:
      url=http://www.sonatype.org/downloads/nexus-latest-bundle.tar.gz
      dest=/root/nexus.tgz
  - unarchive:
      copy=no
      src=/root/nexus.tgz
      dest=/root/
  - apt:
      name=openjdk-7-jre
      state=present

# doc: http://books.sonatype.com/nexus-book/reference/install.html