---
- hosts: debian:&nexus
  tasks:
  - get_url:
      url=http://www.sonatype.org/downloads/nexus-latest-bundle.tar.gz
      dest=/root/nexus.tgz
  - unarchive:
      copy=no
      src=/root/nexus.tgz
      dest=/root/