---
- hosts: debian:&nexus
  tasks:
  - get_url:
      url=http://www.sonatype.org/nexus/thank-you-for-downloading/?dl=tgz
      dest=/root/nexus.tgz
  - unarchive:
      copy=no
      src=/root/nexus.tgz
      dest=/root/nexus