---
- include: apache/playbook.yml
- include: btsync/playbook.yml
- include: docker/playbook.yml
- include: gitd/playbook.yml
- include: jenkins/playbook.yml
- include: nexus/playbook.yml
- include: nginx/playbook.yml
- include: pypiserver/playbook.yml
- include: simpleid/playbook.yml

- hosts: all
  tasks:
  - group_by: key=os_{{ ansible_os_family|lower }}