---
- name: enable ferm mods -- put your mods in /etc/ferm.d
  hosts: debian:&fermod
  tasks:
  - file:
      path: /etc/ferm.d
      state: directory
  - shell: if test ! -e /etc/ferm.d/default; then mv /etc/ferm/ferm.conf /etc/ferm.d/default; fi
  - copy:
      src: ferm.conf
      dest: /etc/ferm/ferm.conf
  - name: clear ferm cache
    command: find /var/cache/ferm -mindepth 1 -delete
  - service:
      name: ferm
      state: restarted
