---
- hosts: ubuntu:&analyzer
  handlers:
  - name: restart dhcp server
    service:
      name=isc-dhcp-server
      state=restarted
  vars:
    # openssl passwd -salt salty -1 wireshark
    wireshark_password: $1$salty$7jpBSJ1B8gIX/lHcNH/bw.
  tasks:
  - apt:
      name={{ item }}
      state=present
    with_items:
    - isc-dhcp-server
    - vnc4server
    - xrdp
    - wireshark
    - fluxbox
# wireshark user setup (login: wireshark, password: wireshark)
  - copy:
      src=sudoers
      dest=/etc/sudoers
      mode=440
  - user:
      system=yes
      name=wireshark
      state=present
      password={{ wireshark_password }}
      shell=/bin/bash
  - copy:
      src={{ item.src }}
      dest={{ item.dest }}
      owner=wireshark
      group=wireshark
      mode=700
    with_items:
    - { src: xsession, dest: /home/wireshark/.xsession }
# configure DHCP server
  - copy:
      src={{ item.src }}
      dest={{ item.dest }}
    with_items:
    - { src: isc-dhcp-server, dest: /etc/default/isc-dhcp-server }
    - { src: interfaces, dest: /etc/network/interfaces }
    - { src: dhcpd.conf, dest: /etc/dhcp/dhcpd.conf }
    notify:
    - restart dhcp server
  - service:
      name=isc-dhcp-server
      state=started
# configure NAT
  - copy:
      src=nat.sh
      dest=/root/nat.sh
  - command: /bin/bash /root/nat.sh start
# install charles proxy
  - apt_key:
      url=http://www.charlesproxy.com/packages/apt/PublicKey
      state=present
  - apt_repository:
      repo="deb http://www.charlesproxy.com/packages/apt/ charles-proxy main"
      state=present
      update_cache=yes
  - apt:
      name=charles-proxy
      state=present
