---
- hosts: ubuntu:&analyzer
  tasks:
  - apt:
      name={{ item }}
      state=present
    with_items:
    - vnc4server
    - xrdp
    - wireshark
    - fluxbox
# wireshark user setup
  - user:
      name=wireshark
      state=present
      password={{ password }} # FIXME: password generation
  - copy:
      src=xsession
      dest=/
# TODO: dhcp server setup -- https://help.ubuntu.com/community/isc-dhcp-server
