---
- hosts: ubuntu:&analyzer
  - name: "password"
      prompt: "Enter a password for the user"
      private: yes
      encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it
      confirm: yes
      salt_size: 7
  tasks:
  - apt:
      name={{ item }}
      state=present
    with_items:
    - vnc4server
    - xrdp
    - wireshark
    - fluxbox
  - user:
      name=analyzer
      state=present
      password={{ password }}
  - copy:
      src=xsession
      dest=/
