---
- hosts: ubuntu:&analyzer
  handlers:
  - name: restart dhcp server
    service:
      name=isc-dhcp-server
      state=restarted
  vars:
    # openssl passwd -salt salty -1 watchman
    watchman_password: $1$salty$wv8do0w7u7j2GkyAQ.81P0
  tasks:
  - apt:
      name={{ item }}
      state=present
    with_items:
    - isc-dhcp-server
    - vnc4server
    - xrdp
    - wireshark
# "watchman" user setup (login: watchman, password: watchman)
  - copy:
      src=sudoers
      dest=/etc/sudoers
      mode=440
  - user:
      name=watchman
			group=admin
      state=present
      password={{ watchman_password }}
      shell=/bin/bash
  - copy:
      src={{ item.src }}
      dest={{ item.dest }}
      owner=watchman
      group=watchman
      mode=700
    with_items:
    - { src: xsession, dest: /home/watchman/.xsession }
# configure DHCP server
  - copy:
      src={{ item.src }}
      dest={{ item.dest }}
    with_items:
    - { src: isc-dhcp-server, dest: /etc/default/isc-dhcp-server }
    - { src: interfaces, dest: /etc/network/interfaces }
    - { src: dhcpd.conf, dest: /etc/dhcp/dhcpd.conf }
    notify:
    - restart dhcp server
  - service:
      name=isc-dhcp-server
      state=started
# configure NAT
  - copy:
      src=nat.sh
      dest=/root/nat.sh
  - command: /bin/bash /root/nat.sh start
# install charles proxy
  - apt_key:
      url=http://www.charlesproxy.com/packages/apt/PublicKey
      state=present
  - apt_repository:
      repo="deb http://www.charlesproxy.com/packages/apt/ charles-proxy main"
      state=present
      update_cache=yes
  - apt:
      name=charles-proxy
      state=present
# install fluxbox last to generate menus
  - apt:
      name=fluxbox
      state=present
