---
- hosts: ubuntu:&btsync
  vars_files:
  - defaults.yml
  handlers:
  - name: restart btsync
    service:
      name: btsync
      state: restarted
  tasks:
  - user:
      name: btsync
      shell: /bin/false
  - template:
      src: settings.j2
      dest: /etc/btsyncrc
      owner: btsync
      group: btsync
      mode: "400"
  # create service manifest
  - template:
      src: upstart.j2
      dest: /etc/init/btsync.conf
    notify:
    - restart btsync
  # copy binaries
  - copy:
      src: "btsync_{{ btsync_arch|default(btsync_arch_default) }}"
      dest: /usr/local/sbin/btsync
    notify:
    - restart btsync
  # create log directory
  - file:
      name: /var/log/btsync
      state: directory
      owner: btsync
      group: btsync
      mode: "700"
  - name: btsync is started
    service:
      name: btsync
      state: started
      enabled: yes
