---
- name: install gitd
  hosts: ubuntu:&gitd
  vars_files:
  - defaults.yml
  tasks:
  - apt:
      name: git
      state: present
  - template:
      src: upstart.j2
      dest: /etc/init/gitd.conf
  - user:
      name: git
      shell: /usr/bin/git-shell
  - file:
      name: /home/git/.ssh
      state: directory
      mode: "700"
      owner: git
      group: git
  - copy:
      src: "{{ gitd_authorized_keys_path|default(gitd_authorized_keys_path_default) }}"
      dest: /home/git/.ssh/authorized_keys
      owner: git
      group: git
  - service:
      name: gitd
      state: started
      enabled: yes
