---
- hosts: ubuntu:&simpleid
  tasks:
  - get_url:
      url=http://downloads.sourceforge.net/simpleid/simpleid-0.9.1.tar.gz
      dest=/root/
  - unarchive:
      copy=no
      src=/root/simpleid-0.9.1.tar.gz
      dest=/var/cache
  - file:
      dest=/var/cache/simpleid
      owner=www-data
      group=www-data
  - file:
      src=/var/cache/simpleid/www
      dest=/var/www/simpleid
      state=link
  - template:
      src=config.php.j2
      dest=/var/cache/simpleid/www/config.php
  - copy:
      src={{ simplid_identities_path }}/
      dest=/var/cache/simpleid/identities/
      owner=www-data
      group=www-data
  - apt:
      name=php5-fpm
      state=present
  - service:
      name=php5-fpm
      state=started
      enabled=yes