---
- hosts: ubuntu:&simpleid
  tasks:
  - get_url:
      url=http://downloads.sourceforge.net/simpleid/simpleid-0.9.1.tar.gz
      dest=/root/
  - file:
      path={{ simple_htmlpath }}
      type=directory
      owner=www-data
      group=www-data
  - unarchive:
      copy=no
      src=/root/simpleid-0.9.1.tar.gz
      dest={{ simpleid_htmlpath }}/