---
- hosts: ubuntu:&simpleid
  tasks:
  - get_url:
      url=http://downloads.sourceforge.net/simpleid/simpleid-0.9.1.tar.gz
      dest=/root/
  - unarchive:
      copy=no
      src=/root/simpleid-0.9.1.tar.gz
      dest={{ simpleid_wwwpath }}/
  - apt:
      name=php5-fpm
      state=present
  - service:
      name=php5-fpm
      state=started