---
- hosts: debian:ubuntu:&nginx
  vars_files:
  - defaults.yml
  handlers:
  - name: reload nginx
    service:
      name=nginx
      state=reloaded
  tasks:
  - apt:
      name=nginx
      state=present
  - name: copy nginx conf
    copy:
      src={{ nginx_confd_path|default(nginx_confd_path_default) }}/
      dest=/etc/nginx/conf.d/
    notify:
    - reload nginx
  - copy:
      src={{ nginx_crt_path|default(nginx_crt_path_default) }}/
      dest=/etc/nginx/crt
  - service:
      name=nginx
      state=started
      enabled=yes