---

- name: install nginx
  hosts: debian:ubuntu:&nginx
  vars_files:
  - defaults.yml
  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
  - name: clear ferm cache
    command: find /var/cache/ferm -mindepth 1 -delete
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  #########
  # nginx #
  #########
  - apt:
      name: nginx
      state: present
  - synchronize:
      src: "{{ nginx_sites_path|default(nginx_sites_path_default) }}/"
      dest: /etc/nginx/sites-enabled/
      delete: yes
    notify:
    - reload nginx
  - synchronize:
      src: "{{ nginx_crt_path|default(nginx_crt_path_default) }}/"
      dest: /etc/nginx/crt
      delete: yes
    notify:
    - reload nginx
  - service:
      name: nginx
      state: started
      enabled: yes
  ########
  # ferm #
  ########
  - stat:
      path: /etc/ferm.d
    register: st
  - name: add nginx ferm mod
    template:
      src: ferm.j2
      dest: /etc/ferm.d/nginx
    notify:
    - clear ferm cache
    - reload ferm

- name: uninstall nginx
  hosts: debian:ubuntu:&no-nginx
  handlers:
  - name: clear ferm cache
    command: find /var/cache/ferm -mindepth 1 -delete
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  #########
  # nginx #
  #########
  - service:
      name: nginx
      state: stopped
      enabled: no
    ignore_errors: yes
  - apt:
      name: nginx
      state: absent
      purge: yes
  ########
  # ferm #
  ########
  - name: remove nginx ferm mod
    file:
      path: /etc/ferm.d/nginx
      state: absent
    notify:
    - clear ferm cache
    - reload ferm
