---
- hosts: ubuntu:&nginx
  handlers:
  - name: reload nginx
    service:
      name=nginx
      state=reloaded
  tasks:
  - apt:
      name=nginx
      state=present
  - name: copy nginx default conf
    copy:
      src={{ nginx_default_path }}
      dest=/etc/nginx/sites-enabled/
    notify:
    - reload nginx
  - copy:
      src={{ nginx_crt_path }}/
      dest=/etc/nginx/crt
  - service:
      name=nginx
      state=started
      enabled=yes