---
- hosts: debian:ubuntu:&nginx
  vars_files:
  - defaults.yml
  handlers:
  - name: reload nginx
    service:
      name=nginx
      state=reloaded
  tasks:
  - apt:
      name=nginx
      state=present
  - name: copy nginx conf
    copy:
      src={{ nginx_sites_path|default(nginx_sites_path_default) }}/
      dest=/etc/nginx/sites-enabled/
    notify:
    - reload nginx
  - copy:
      src={{ nginx_crt_path|default(nginx_crt_path_default) }}/
      dest=/etc/nginx/crt
  - service:
      name=nginx
      state=started
      enabled=yes

######################
# add nginx ferm mod #
######################
- hosts: debian:&ferm:&nginx
  vars_files:
  - defaults.yml
  handlers:
  - name: reload ferm
    service:
      name=ferm
      state=reloaded
  tasks:
  - template:
      src=ferm.j2
      dest=/etc/ferm.d/nginx
    notify:
    - reload ferm
  - apt:
      name=git
      state=present
