---

- name: install pypiserver
  hosts: debian:ubuntu:&pypiserver
  vars_files:
  - defaults.yml
  handlers:
  - name: restart pypiserver
    service:
      name: pypiserver
      state: restarted
  - name: clear ferm cache
    command: find /var/cache/ferm -mindepth 1 -delete
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  ##############
  # pypiserver #
  ##############
  - apt:
      name: python-pip
      state: present
  - pip:
      name: "{{ item }}"
      state: present
    with_items:
    - pypiserver
    - passlib
  - user:
      name: pypiserver
      state: present
      system: yes
  - file:
      name: /var/cache/pypiserver
      state: directory
      owner: pypiserver
      group: pypiserver
  - template:
      src: upstart.j2
      dest: /etc/init/pypiserver.conf
    when:
    - ansible_distribution == "Ubuntu"
    notify:
    - restart pypiserver
  - template:
      src: sysv.j2
      dest: /etc/init.d/pypiserver
      mode: "755"
    when:
    - ansible_distribution == "Debian"
    notify:
    - restart pypiserver
  - file:
      name: /etc/pypiserver
      state: directory
      owner: pypiserver
      group: pypiserver
      mode: "700"
  - copy:
      src: "{{ pypiserver_htaccess_path|default(pypiserver_htaccess_path_default) }}"
      dest: /etc/pypiserver
      owner: pypiserver
      group: pypiserver
      mode: "600"
    notify:
    - restart pypiserver
  - service:
      name: pypiserver
      state: started
      enabled: yes
  ########
  # ferm #
  ########
  - stat:
      path: /etc/ferm.d
    register: st
  - name: add pypiserver ferm mod on non-local listen address
    template:
      src: ferm.j2
      dest: /etc/ferm.d/pypiserver
    when: "st.stat.exists and '{{ pypiserver_listen_address|default(pypiserver_listen_address_default) }}' != '127.0.0.1'"
    notify:
    - clear ferm cache
    - reload ferm
  - name: remove pypiserver ferm mod on local listen address
    file:
      path: /etc/ferm.d/pypiserver
      state: absent
    when: "st.stat.exists and '{{ pypiserver_listen_address|default(pypiserver_listen_address_default) }}' == '127.0.0.1'"
    notify:
    - clear ferm cache
    - reload ferm
