---
- hosts: ubuntu:&pypiserver
  tasks:
  - apt:
      name=pip
      state=present
  - pip:
      name=pypiserver
      state=present
  - copy:
      src=pypiserver.conf
      dest=/etc/init
  - service:
      name=pypiserver
      state=started