---
- hosts: ubuntu:&pypiserver
  handlers:
  - name: restart pypiserver
    service:
      name=pypiserver
      state=restarted
  tasks:
  - apt:
      name=python-pip
      state=present
  - pip:
      name={{ item }}
      state=present
    with_items:
    - pypiserver
    - passlib
  - user:
      name=pypi
      shell=/bin/false
  - file:
      name=/home/pypi/packages
      state=directory
      owner=pypi
      group=pypi
  - template:
      src=pypiserver.j2
      dest=/etc/init/pypiserver.conf
    notify:
    - restart pypiserver
  - copy:
      src={{ pypiserver_htaccess_path }}
      dest=/home/pypi
      owner=pypi
      group=pypi
      mode=700
    notify:
    - restart pypiserver
  - service:
      name=pypiserver
      state=started