---
- hosts: debian:ubuntu:&pypiserver
  vars_files:
  - defaults.yml
  handlers:
  - name: restart pypiserver
    service:
      name=pypiserver
      state=restarted
  tasks:
  - apt:
      name=python-pip
      state=present
  - pip:
      name={{ item }}
      state=present
    with_items:
    - pypiserver
    - passlib
  - user:
      name=pypi
      shell=/bin/false
  - file:
      name=/home/pypi/packages
      state=directory
      owner=pypi
      group=pypi
  - template:
      src=pypiserver.conf.j2
      dest=/etc/init/pypiserver.conf
    when:
    - ansible_distribution == "Ubuntu"
    notify:
    - restart pypiserver
  - template:
      src=pypiserver.j2
      dest=/etc/init.d/pypiserver
      mode=755
    when:
    - ansible_distribution == "Debian"
    notify:
    - restart pypiserver
  - copy:
      src={{ pypiserver_htaccess_path|default(pypiserver_htaccess_path_default) }}
      dest=/home/pypi
      owner=pypi
      group=pypi
      mode=700
    notify:
    - restart pypiserver
  - service:
      name=pypiserver
      state=started
      enabled=yes

########################
# add jenkins ferm mod #
########################
- hosts: debian:&ferm:&pypiserver
  vars_files:
  - defaults.yml
  handlers:
  - name: reload ferm
    service:
      name=ferm
      state=reloaded
  tasks:
  - template:
      src=ferm.j2
      dest=/etc/ferm.d/pypiserver
    when: "{{ pypiserver_listen_address|default(pypiserver_listen_address_default) }}" != "127.0.0.1"
    notify:
    - reload ferm
