---

- name: install pypiserver
  hosts: debian:ubuntu:&pypiserver
  vars_files:
  - defaults.yml
  handlers:
  - name: restart pypiserver
    service:
      name: pypiserver
      state: restarted
  tasks:
  - apt:
      name: python-pip
      state: present
  - pip:
      name: "{{ item }}"
      state: present
    with_items:
    - pypiserver
    - passlib
  - user:
      name: pypiserver
      state: present
      system: yes
  - file:
      name: /var/cache/pypiserver
      state: directory
      owner: pypiserver
      group: pypiserver
  - template:
      src: upstart.j2
      dest: /etc/init/pypiserver.conf
    when:
    - ansible_distribution == "Ubuntu"
    notify:
    - restart pypiserver
  - template:
      src: sysv.j2
      dest: /etc/init.d/pypiserver
      mode: "755"
    when:
    - ansible_distribution == "Debian"
    notify:
    - restart pypiserver
  - file:
      name: /etc/pypiserver
      state: directory
      owner: pypiserver
      group: pypiserver
      mode: "700"
  - copy:
      src: "{{ pypiserver_htaccess_path|default(pypiserver_htaccess_path_default) }}"
      dest: /etc/pypiserver
      owner: pypiserver
      group: pypiserver
      mode: "600"
    notify:
    - restart pypiserver
  - service:
      name: pypiserver
      state: started
      enabled: yes

- name: manage pypiserver ferm mod
  hosts: debian:&fermod:&pypiserver
  vars_files:
  - defaults.yml
  handlers:
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  - name: add pypiserver ferm mod if non-local
    template:
      src: ferm.j2
      dest: /etc/ferm.d/pypiserver
    when: "'{{ pypiserver_listen_address|default(pypiserver_listen_address_default) }}' !=  '127.0.0.1'"
    notify:
    - reload ferm
  - name: remove pypiserver ferm mod if local
    file:
      path: /etc/ferm.d/pypiserver
      state: absent
    when: "'{{ pypiserver_listen_address|default(pypiserver_listen_address_default) }}' ==  '127.0.0.1'"
    notify:
    - reload ferm
