---
- hosts: ubuntu:&pypiserver
  handlers:
  - name: reload pypiserver
    service:
      name=pypiserver
      state=reloaded
  tasks:
  - apt:
      name=python-pip
      state=present
  - pip:
      name=pypiserver
      state=present
  - user:
      name=pypi
      shell=/bin/false
  - file:
      name=/home/pypi/packages
      state=directory
      owner=pypi
      group=pypi
  - copy:
      src=pypiserver.conf
      dest=/etc/init
    notify:
    - reload pypiserver
  - copy:
      src={{ htaccess_path }}
      dest=/home/pypi
      owner=pypi
      group=pypi
      mode=700
  - service:
      name=pypiserver
      state=started