---

########################
# setup LTS repository #
########################
- hosts: debian:ubuntu:&jenkinslts
  tasks:
  - apt_key:
      url=http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
      state=present
  - apt_repository:
      repo='deb http://pkg.jenkins-ci.org/debian-stable binary/'
      state=present
      update_cache=yes

#############################
# setup DEV repository #
#############################
- hosts: debian:ubuntu:&jenkins
  tasks:
  - apt_key:
      url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
      state=present
  - apt_repository:
      repo='deb http://pkg.jenkins-ci.org/debian binary/'
      state=present
      update_cache=yes

###################
# install service #
###################
- hosts: debian:ubuntu:&jenkins*
  vars_files:
  - defaults.yml
  handlers:
  - name: restart jenkins
    service:
      name=jenkins
      state=restarted
  tasks:
  # pre-install JRE7 to bypass JRE6
  - apt:
      name=openjdk-7-jre-headless
      state=present
  # install jenkins
  - apt:
      name=jenkins
      state=present
  - template:
      src=jenkins.j2
      dest=/etc/default/jenkins
      mode=644
    notify:
    - restart jenkins
  # copy jenkins keys
  - file:
      name=/var/lib/jenkins/.ssh
      state=directory
      mode=700
      owner=jenkins
      group=jenkins
  - copy:
      src={{ jenkins_sshpath }}/
      dest=/var/lib/jenkins/.ssh/
  # copy patched plugins
  - copy:
      src=plugins/
      dest=/var/lib/jenkins/plugins/
    notify:
    - restart jenkins # FIXME: necessary?
  # start service
  - service:
      name=jenkins
      state=started
      enabled=yes

########################
# add jenkins ferm mod #
########################
- hosts: debian:&ferm:&jenkins*
  vars_files:
  - defaults.yml
  handlers:
  - name: reload ferm
    service:
      name=ferm
      state=reloaded
  tasks:
  - template:
      src=ferm.j2
      dest=/etc/ferm.d/jenkins
    notify:
    - reload ferm
  - apt:
      name=git
      state=present