---

- name: setup LTS repository
  hosts: debian:ubuntu:&jenkinslts
  vars_files:
  - defaults.yml
  tasks:
  - apt_key:
      url: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
      state: present
    environment: "{{ jenkins_environment|default(jenkins_environment_default) }}"
  - apt_repository:
      repo: "deb http://pkg.jenkins-ci.org/debian-stable binary/"
      state: present
      update_cache: yes

- name: setup standard repository
  hosts: debian:ubuntu:&jenkins
  vars_files:
  - defaults.yml
  tasks:
  - apt_key:
      url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
      state: present
    environment: "{{ jenkins_environment|default(jenkins_environment_default) }}"
  - apt_repository:
      repo: "deb http://pkg.jenkins-ci.org/debian binary/"
      state: present
      update_cache: yes

- name: install jenkins
  hosts:
  - debian:&jenkins
  - ubuntu:&jenkins
  - debian:&jenkinslts
  - ubuntu:&jenkinslts
  vars_files:
  - defaults.yml
  handlers:
  - name: restart jenkins
    service:
      name: jenkins
      state: restarted
  - name: clear ferm cache
    command: find /var/cache/ferm -mindepth 1 -delete
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  ###########
  # jenkins #
  ###########
  # pre-install JRE7 to bypass JRE6
  - apt:
      name: openjdk-7-jre-headless
      state: present
  # install jenkins
  - apt:
      name: jenkins
      state: present
  - template:
      src: settings.j2
      dest: /etc/default/jenkins
      mode: "644"
    notify:
    - restart jenkins
  # copy jenkins keys
  - file:
      name: /var/lib/jenkins/.ssh
      state: directory
      mode: "700"
      owner: jenkins
      group: jenkins
  - copy:
      src: "{{ jenkins_sshpath|default(jenkins_sshpath_default) }}/"
      dest: /var/lib/jenkins/.ssh/
  # start service
  - service:
      name: jenkins
      state: started
      enabled: yes
  #############
  # logrotate #
  #############
  - stat:
      path: /etc/logrotate.d
    register: st
  - copy:
      src: logrotate
      dest: /etc/logrotate.d/jenkins
    when: st.stat.exists
  ########
  # ferm #
  ########
  - stat:
      path: /etc/ferm.d
    register: st
  - name: add jenkins ferm mod on non-local listen address
    template:
      src: ferm.j2
      dest: /etc/ferm.d/jenkins
    when: "st.stat.exists and '{{ jenkins_listen_address|default(jenkins_listen_address_default) }}' != '127.0.0.1'"
    notify:
    - clear ferm cache
    - reload ferm
  - name: remove jenkins ferm mod on local listen address
    file:
      path: /etc/ferm.d/jenkins
      state: absent
    when: "st.stat.exists and '{{ jenkins_listen_address|default(jenkins_listen_address_default) }}' == '127.0.0.1'"
    notify:
    - clear ferm cache
    - reload ferm
