---
- hosts: debian:ubuntu:&jenkins
  handlers:
  - name: restart jenkins
    service:
      name=jenkins
      state=restarted
  tasks:
  # install jenkins
  - apt_key:
      url=http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
      state=present
  - apt_repository:
      repo='deb http://pkg.jenkins-ci.org/debian-stable binary/'
      state=present
      update_cache=yes
  - apt:
      name=jenkins
      state=present
  # copy jenkins keys
  - file:
      name=/var/lib/jenkins/.ssh
      state=directory
      mode=700
      owner=jenkins
      group=jenkins
  - copy:
      src={{ item.src }}
      dest=/var/lib/jenkins/.ssh/{{ item.dest }}
    with_items:
    - { src: "{{ private_key_path }}", dest: id_rsa }
    - { src: "{{ public_key_path }}", dest: id_rsa.pub }
  - template:
      src=jenkins/jenkins.j2
      dest=/etc/default/jenkins
      mode=644
    notify:
    - restart jenkins
  # start service
  - service:
      name=jenkins
      state=started
      enabled=yes
