---
- hosts: debian:&elk
  tasks:
  # pre-install JRE7 to bypass JRE6
  - apt:
      name=openjdk-7-jre-headless
      state=present
  #################
  # elasticsearch #
  #################
  - apt_key:
      url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
      state=present
  - apt_repository:
      repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
      state=present
      update_cache=yes
  - apt:
      name=elasticsearch
      state=present
  ##########
  # kibana #
  ##########
  - get_url:
      url=https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
      dest=/var/tmp
  - unarchive:
      src=/var/tmp/kibana-4.0.1-linux-x64.tar.gz
      dest=/var/tmp/
      copy=no