---
- hosts: debian:&elk
  handlers:
  - name: restart logstash
    service:
      name: logstash
      state: restarted
  - name: restart kibana
    service:
      name: kibana
      state: restarted
  - name: reload rsyslog
    service:
      name: rsyslog
      state: reloaded
  vars_files:
  - defaults.yml
  tasks:
  # pre-install JRE7 to bypass JRE6
  - apt:
      name: openjdk-7-jre-headless
      state: present
  # add ELK key for both logstash and elasticsearch
  - apt_key:
      url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
      state: present
  ############
  # logstash #
  ############
  - apt_repository:
      repo: "deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"
      state: present
      update_cache: yes
  - apt:
      name: logstash=1.4.2*
      state: present
  - copy:
      src: logstash.settings
      dest: /etc/logstash/conf.d/syslog_to_elasticsearch.conf
    notify:
    - restart logstash
  - service:
      name: logstash
      state: started
      enabled: yes
  - copy:
      src: logstash.rsyslog.conf
      dest: /etc/rsyslog.d/logstash.conf
    notify:
    - reload rsyslog
  #################
  # elasticsearch #
  #################
  - apt_repository:
      repo: "deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
      state: present
      update_cache: yes
  - apt:
      name: elasticsearch=1.4.4
      state: present
  - service:
      name: elasticsearch
      state: started
      enabled: yes
  ##########
  # kibana #
  ##########
  - file:
      path: /opt
      mode: "755"
      owner: root
      group: root
      state: directory
  - get_url:
      url: "https://download.elasticsearch.org/kibana/kibana/kibana-{{ kibana_version }}.tar.gz"
      dest: /var/tmp
  - unarchive:
      src: "/var/tmp/kibana-{{ kibana_version }}.tar.gz"
      dest: /opt
      copy: no
  - user:
      name: kibana
      state: present
      system: yes
  - template:
      src: kibana.sysv.j2
      dest: /etc/init.d/kibana
      mode: "755"
    notify:
    - restart kibana
  - service:
      name: kibana
      state: started
      enabled: yes

#####################
# add ELK ferm mods #
#####################
- hosts: debian:&ferm:&elk
  vars_files:
  - defaults.yml
  handlers:
  - name: reload ferm
    service:
      name: ferm
      state: reloaded
  tasks:
  - template:
      src: kibana.ferm.j2
      dest: /etc/ferm.d/kibana
    when: "'{{ kibana_listen_address|default(kibana_listen_address_default) }}' !=  '127.0.0.1'"
    notify:
    - reload ferm
  - copy:
      src: logstash.ferm
      dest: /etc/ferm.d/logstash
    notify:
    - reload ferm
