---
- hosts: macosx
  tasks:
  - name: set HostName
    command: scutil --set HostName {{ osx_hostname }}
    sudo: yes
  - name: set ComputerName
    command: scutil --set ComputerName {{ osx_computername|default(osx_hostname) }}
    sudo: yes
  - name: set LocalHostName -- used by Bonjour and visible through file sharing services like AirDrop
    command: scutil --set LocalHostName {{ osx_localhostname|default(osx_hostname) }}
    sudo: yes
  - name: clear user logs
    command: find ~/Library/Logs -mindepth 1 -delete
  - name: clear user caches
    command: find ~/Library/Caches -mindepth 1 -delete
  - name: clean empty folders in ~/Libray
    command: find ~/Library -mindepth 4 -type d -empty
    ignore_errors: yes
  - name: clear system logs
    command: find /Library/Logs -mindepth 1 -delete
    sudo: yes
  - name: clear system log archives
    command: find /var/log -type f -name "*.log.*" -delete
    sudo: yes
