---
- hosts: macosx
  tasks:
  - name: set ComputerName
    command: scutil --set ComputerName {{ osx_computername }}
    sudo: yes
  - name: set HostName
    command: scutil --set HostName {{ osx_hostname|default(osx_computername + ".local") }}
    sudo: yes
  - name: set LocalHostName -- used by Bonjour and visible through file sharing services like AirDrop
    command: scutil --set LocalHostName {{ osx_localhostname|default(osx_computername) }}
    sudo: yes
#  - name: set the icon size of Dock items to 50px
#    command: defaults write com.apple.dock tilesize -int 50
#  - name: show indicator lights for open applications in the Dock
#    command: defaults write com.apple.dock show-process-indicators -bool true


# ref: https://github.com/mathiasbynens/dotfiles/blob/master/.osx