---
- hosts: httpd
  when: ansible_os_family == "Debian"
  tasks:
  - apt:
      name=apache2
      state=present
  - copy:
      src={{ index_path }}
      dest=/var/www/html/index.html
  - service:
      name=apache2
      state=started
      enabled=yes