---
- hosts: ubuntu:&apache
  tasks:
  - apt:
      name=apache2
      state=present
  - copy:
      src={{ apache_htmlpath }}
      dest=/var/www/
  - service:
      name=apache2
      state=started
      enabled=yes

- hosts: ubuntu:&noapache
  tasks:
  - apt:
      name=apache2
      state=absent
      purge=yes