---
- hosts: ubuntu:&apache
  tasks:
  - apt:
      name=apache2
      state=present
  - service:
      name=apache2
      state=started
      enabled=yes

- hosts: ubuntu:&no-apache
  tasks:
  - apt:
      name=apache2
      state=absent
      purge=yes