---
- name: install apache
  hosts: ubuntu:&apache
  tasks:
  - apt:
      name: apache2
      state: present
  - service:
      name: apache2
      state: started
      enabled: yes

- name: uninstall apache
  hosts: ubuntu:&no-apache
  tasks:
  - service:
      name: apache2
      state: stopped
      enabled: no
    ignore_errors: yes
  - apt:
      name: apache2
      state: absent
      purge: yes